### ISSUE TITLE
Outdated Viral Database

### ISSUE THREAD

**Issue by DarioS** [dmarron/virdetect#1]
The file I downloaded seems to be the same old one described by [the journal article](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-020-6483-6).

> The VirDetect database comprised of 1893 manually-curated vertebrate virus reference genomes from GenBank, downloaded on December 16, 2015 … Vertebrate viral FASTA (1894 viruses) was downloaded from GenBank and masked for increased specificity.

```r
library(ShortRead)
genomes <- readFasta("virus_masked_hg38.fa")
length(genomes)
[1] 1894
```

May a new release be made soon with masked genomes of recently deposited viruses? I realise there are tools provided for making your own, but hg38 analysis is so common that it would be nice if each end-user didn't need to do it themselves. Also, the tools don't seem to have option documentation - `java -cp simulateReads.jar -h` doesn't show any command summary. For example, if the user has 150 bases pairs of reads, which are nowadays more common than 75 bases read lengths, it's unclear how to specify that as a parameter of the simulation or if you recommend the simulation should use the read length corresponding to the user's data set.

**Comment by sararselitsky** [comment]
Hi Dario,

Do you have an updated reference you could send us a link to? I was just searching through GenBank and couldn’t find a comparable one.

David, can you answer Dario’s question about changing the size of the read length for simulation?

Please let us know if I missed any of your questions or if you have other questions.

Thank you for your interest in VirDetect!

Sara

**Comment by DarioS** [comment]
Oh, I didn't mean that GenBank is outdated. I mean that the masked version of the viral genomes sourced from Genbank in 2015 that is distributed by this software is, however. I was hoping that the viruses could be re-extracted and processed into a usable format this year. There would be many new ones since 2015 and perhaps some old ones might have improvements to their sequences.

**Comment by dmarron** [comment]
Hi Dario,

Currently simulateReads.java is not parameterizable, but I think that it is a good idea to make it so.  I will upload a new jar file shortly that allows the user to parameterize the length of the simulated reads.

David

**Comment by dmarron** [comment]
Hi Dario,

I have uploaded a new version of simulateReads.jar that allows the user to customize the length of the simulated reads used for masking by specifying the read length as an optional third parameter. 

In terms of uploading a more recent viral database that is newer than the one sourced from the 2015 Genbank, making a newer database is a possibility but I would not want to upload it as the recommended virdetect database without testing the new or updated virus strains as thoroughly as the ones from the current database were tested, which is fairly involved.  For the near future, I would recommend using the tools for making a custom masked genome on the newer database you wish to use (or the new virus strains that you wish to add).

David
