### ISSUE TITLE
hg38_noEBV.fa not found

### ISSUE THREAD

**Issue by MeteorLiu96** [dmarron/virdetect#2]
Hi,dmarron
     I‘m interested in your virdetect and wanna have a try. But I didn't found hg38_noEBV.fa in reference file. Could you help me finding it. Or could you just give me an advice how to get a correct hg38.fa with no EBV version? Since there are so many versions of hg38.fa files in NCBI.  @dmarron 

I would greatly appreciate if you could help me with this problem.
Thank you

**Comment by dmarron** [comment]
Sure, I can give you more specific instructions on how to get hg38.fa without EBV.  There are a number of sources of hg38, but one way you can get it is from UCSC with the command:
wget https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz
Then extract with:
gunzip hg38.fa.gz
This will give you a version of hg38.fa that already does not have EBV.  The virdetect manual just specifies no EBV because some versions of hg38 have EBV in it (and sometimes even other virus strains) that should be removed before running virdetect, or virdetect will be unable to find those viruses.

David

**Comment by MeteorLiu96** [comment]
Thank you very much David. I just met another problem that is the follow:
java -Xmx4G -cp picard-1.92.jar:sam-1.92.jar:countStarViralAlignments.jar countStarViralAlignments <sample_name> STAR_virus_Aligned.out.sam viralReadCounts.txt # 8 G memory
What kind of sample name should I fill in? SRRXXXXXX or something else? Sorry, I have no idea about it.

**Comment by dmarron** [comment]
The sample name can be anything you would like (such as the fastq name).  It is just there to distinguish between different samples if you are running virdetect on multiple samples.

**Comment by MeteorLiu96** [comment]
Hi，David
Thank you. I just try to run one sample all by default and delete the name like this:
java -Xmx4G -cp picard-1.92.jar:sam-1.92.jar:countStarViralAlignments.jar countStarViralAlignments  STAR_virus_Aligned.out.sam viralReadCounts.txt
And it said error in finding countStarViralAlignments :no such file or dir. 
Then I tried this:
java -Xmx4G -cp picard-1.92.jar:sam-1.92.jar:/mnt/d/SRA/Biosoft/WorkDir/java/countStarViralAlignments.jar countStarViralAlignments  STAR_virus_Aligned.out.sam viralReadCounts.txt
And it said Exception in thread "main" java.lang.NoClassDefFoundError.
Forgive me for being a novice.
Thank you again

**Comment by dmarron** [comment]
I think you may be getting the error no such file or dir because the program is expecting something for the sample_name parameter.  Could you try moving all the jar files into the same folder, and then running the command java -Xmx4G -cp picard-1.92.jar:sam-1.92.jar:countStarViralAlignments.jar countStarViralAlignments sample STAR_virus_Aligned.out.sam viralReadCounts.txt?

**Comment by MeteorLiu96** [comment]
It works. But I get the error as follow:
Usage: java countStarViralAlignments sampleID STAR_virus_Aligned.out.sam viralReadCounts.txt mismatches_allowed
My workflow is:
STAR --runThreadN 6 --genomeDir HumanIndex --readFilesIn /mnt/d/SRA/sradata/SRR2016932_1.fastq.gz /mnt/d/SRA/sradata/SRR2016932_2.fastq.gz --readFilesCommand zcat --outFilterMultimapNmax 1000 --outSAMunmapped Within --outFileNamePrefix STAR_
sh awk_column3_star.sh STAR_Aligned.out.sam > unaligned.sam
sh awk_unalignedfq_1.sh unaligned.sam > unaligned_1.fastq && sh awk_unalignedfq_2.sh unaligned.sam > unaligned_2.fastq
STAR --genomeDir VirusIndex --readFilesIn unaligned_1.fastq unaligned_2.fastq --runThreadN 16 --outFilterMismatchNmax 4 --outFilterMultimapNmax 1000 --limitOutSAMoneReadBytes 1000000 --outFileNamePrefix STAR_virus_
Then I got unaligned.sam unaligned_1.fastq unaligned_2.fastq STAR_Aligned.out.sam STAR_virus_Aligned.out.sam.  Could you please take an example for me?  Which one of these above should I use? Or anything else?

**Comment by dmarron** [comment]
That is strange that you got that error with countStarViralAlignments.  It looks like the program is finding the wrong number of parameters.  Could you paste the exact command you used to run countStarViralAlignments?  The other commands you posted for the virdetect workflow all look correct.  You should be using STAR_virus_Aligned.out.sam, that is the sam file with all the viral alignments.

**Comment by MeteorLiu96** [comment]
My java command is：
java -Xmx4G -cp picard-1.92.jar:sam-1.92.jar:countStarViralAlignments.jar STAR_Aligned.out.sam countStarViralAlignments  STAR_virus_Aligned.out.sam viralReadCounts.txt
I think maybe that is  the problem. I will try with STAR_virus_Aligned.out.sam soon. 
Thank you.

**Comment by dmarron** [comment]
I think the problem is that you you have a "STAR_Aligned.out.sam" between countStarViralAlignments.jar and countStarViralAlignments that should not be there.  Try the command:
java -Xmx4G -cp picard-1.92.jar:sam-1.92.jar:countStarViralAlignments.jar countStarViralAlignments sample STAR_virus_Aligned.out.sam viralReadCounts.txt

David

**Comment by MeteorLiu96** [comment]
It works! My gratitude to you for all you have done for me!  The last question---
I got a viralRTable.txt when visualization, what does the col2&col3 mean? And it seems there are at least 6 columns in viralRTable.txt from your Rscript, but I got only 5 columns, which seems strange.
My visualization command is
java -Xmx4G -cp picard-1.92.jar:sam-1.92.jar:makeRTable.jar makeRTable sample Human_endogenous_retrovirus_K113_complete_genome_unmasked STAR_virus.Aligned.out.sam viralRTable.txt
Here is the viralRTable.txt:
1	1	0,1,0,0	sample	gi|548558394|ref|NC_022518.1|Human_endogenous_retrovirus_K113_complete_genome_unmasked
2	1	0,0,0,1	sample	gi|548558394|ref|NC_022518.1|Human_endogenous_retrovirus_K113_complete_genome_unmasked
3	1	0,1,0,0	sample	gi|548558394|ref|NC_022518.1|Human_endogenous_retrovirus_K113_complete_genome_unmasked
4	1	0,0,0,1	sample	gi|548558394|ref|NC_022518.1|Human_endogenous_retrovirus_K113_complete_genome_unmasked
5	1	0,0,0,1	sample	gi|548558394|ref|NC_022518.1|Human_endogenous_retrovirus_K113_complete_genome_unmasked
6	1	0,0,0,1	sample	gi|548558394|ref|NC_022518.1|Human_endogenous_retrovirus_K113_complete_genome_unmasked
7	1	0,0,0,1	sample	gi|548558394|ref|NC_022518.1|Human_endogenous_retrovirus_K113_complete_genome_unmasked
8	1	1,0,0,0	sample	gi|548558394|ref|NC_022518.1|Human_endogenous_retrovirus_K113_complete_genome_unmasked
......

**Comment by dmarron** [comment]
Here is what each tab delimited column of the table means:
col1: position in virus strain
col2: total number of reads aligned to that position (read count)
col3: A,T,C,G counts of reads aligned to that position
col4: sample ID
col5: strain name

I believe that when the R script sums c[3:6], it is adding together the counts of the 4 nucleotides A,T,C, and G of tab delimited column 3, not looking at 6th tab delimited column, if that makes sense.  You are correct that there are only 5 tab delimited columns.

**Comment by MeteorLiu96** [comment]
Thank you so much! David
